server:
  port: 3003
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/

spring:
  application:
    name: qr-channel
  zipkin:
    base-url: http://localhost:3006